version: "3.8"

services:
  web:
    build: ./sp2txtbot
    container_name: web-s2t
    command: "python app.py"
    volumes:
      - ./sp2txtbot/:/usr/src/sp2txtbot/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: db-s2t
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data:
