version: "3.8"

services:
  web:
    image: ghcr.io/appxpy/thecbd.ru/web:latest
    container_name: web
    build:
      context: ./sp2txtbot
      dockerfile: Dockerfile.prod
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /home/ubuntu/server/proxy/data/certs/:/usr/src/certs:ro
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - proxy
      - default
  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  prod_postgres_data:

networks:
  proxy:
    external: true
